drop table if exists note;
drop table if exists class;
drop table if exists user_schedule_relation;
drop table if exists schedule_revision;
drop table if exists schedule;

create table if not exists "user"
(
    id       integer generated by default as identity
        constraint user_pk
            primary key,
    login    varchar,
    password varchar
);

alter table "user"
    owner to postgres;

create table if not exists schedule
(
    id            integer generated by default as identity
        constraint schedule_pk
            primary key,
    year          varchar,
    field         varchar,
    academic_year varchar,
    semester      varchar
);

alter table schedule
    owner to postgres;

create table if not exists schedule_revision
(
    id          integer generated by default as identity
        constraint schedule_revision_pk
            primary key,
    date        date    default now() not null,
    schedule_id integer default 0     not null
        constraint schedule_revision_schedule_id_fk
            references schedule
);

alter table schedule_revision
    owner to postgres;

create table if not exists class
(
    id                   integer generated by default as identity
        constraint class_pk
            primary key,
    date                 date,
    start_hour           time,
    end_hour             time,
    name                 varchar,
    lecturer             varchar,
    group_number         varchar,
    class_number         varchar,
    changed              varchar,
    schedule_revision_id integer
        constraint class_schedule_revision_id_fk
            references schedule_revision
);

alter table class
    owner to postgres;

create table if not exists note
(
    id        integer generated by default as identity
        constraint note_pk
            primary key,
    class_id  integer
        constraint note_class_id_fk
            references class,
    author_id integer default 0 not null
        constraint note_user_id_fk
            references "user",
    note_body varchar
);

alter table note
    owner to postgres;

create table if not exists user_schedule_relation
(
    id          integer generated by default as identity,
    user_id     integer not null
        constraint user_schedule_relation_user_id_fk
            references "user",
    schedule_id integer not null
        constraint user_schedule_relation_schedule_id_fk
            references schedule
);

alter table user_schedule_relation
    owner to postgres;

