###
# @name=Add Schedule Version
POST localhost:2013/addScheduleVersion
Content-Type: application/json

{
  "year" : "3z",
  "field" : "IiE",
  "user" : {
    "id" : "",
    "login" : "test",
    "password" :  "sci"
  }
}


###

# @name=Get Current User Schedules
GET localhost:2013/getUserSchedules?login=test&password=sci
Content-Type: application/json

###

# @name=Add note
POST localhost:2013/addNote
Content-Type: application/json

{
  "noteBody" : "Testowa notatka",
  "classId" : "17",
  "User" : {
    "id" : "",
    "login" : "test",
    "password" : "sci"
  }
}

###

# @name=Get Classes
GET localhost:2013/getRevisionClasses?revisionId=1

###

# @name=Delete user schedule relation
DELETE localhost:2013/usersAssignedSchedule?login=test&password=sci&scheduleId=11
