###
# @name=Add Schedule Version
POST localhost:2013/addScheduleVersion
Content-Type: application/json

{
  "year" : "3z",
  "field" : "IiE",
  "user" : {
    "id" : "",
    "login" : "admin",
    "password" :  "admin"
  }
}


###

# @name=Get Current User Schedules
GET localhost:2013/getUserSchedules
Content-Type: application/json

{
  "id" : "",
  "login" : "admin",
  "password" : "admin"
}
